name: Deploy staging website
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Create env file for app
        env:
          ENV_FILE: ${{ secrets.ENV_FILE_STAGING }}
        run: |
          echo $ENV_FILE | base64 -di > .env

      - run: yarn
      - run: yarn run export

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out
  test:
    needs: [build]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: out
          path: out

      - run: yarn global add @synthetixio/synpress
      - run: SECRET_WORDS='${{ secrets.CYPRESS_TESTING_MNEMONIC }}' synpress run --configFile cypress/e2e/customConfig.json --record --key 6a50a203-8831-4ca5-bd99-87c5d5140cfb

  deploy:
    needs: [test]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: out
          path: out

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREATOR_POOLS }}"
          channelId: live
          projectId: swaysocial-one-pager
          target: creatorpools-staging
