name: Cypress tests
on:
  push:
    branches:
      - testing-synpress
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Create env file for app
        env:
          ENV_FILE: ${{ secrets.ENV_FILE_STAGING }}
        run: |
          echo $ENV_FILE | base64 --decode > .env

      - run: yarn
      - run: yarn run export

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out

  test:
    needs: [build]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and run Synpress
        run:  npm i sypress -g
              npm run test:e2e
